### PR TITLE
Fix alert beep on osx

### LINKED ISSUE #96: zazu makes a beep on esc and enter
I've installed zazu on osx 10.12.2, and it makes a beep sound each time I cancel zazu window or press enter. Is it common behavior? Is it configurable?

### PR DESCRIPTION
**Pull request by afaur**
Fixes https://github.com/tinytacoteam/zazu/issues/96

I tested this on my machine and it fixes the issue ( Didn't realize it was this simple :D )
Could you take a look @blainesch or @amjith ?

We probably want to include `esc` as well. (Added)

### CODE REVIEW

**Comment by amjith** [comment]
Glad you added `esc`, I was about to request it.

Works great!! 👍

File: app/components/search.js [hunk 1]
```diff
@@ -26,6 +26,12 @@ const Search = React.createClass({
     }
   },
 
+  handleKeyPress (event) {
+    if (event.keyCode === 13 && event.keyCode === 27) {
```
Comment (bayleedev) [inline app/components/search.js:30]: Should this be a `||` not a `&&` ?

Also can you identify the 13 and 27? Magic numbers are scary :D

~~~ javascript
    const enterKey = 13
    const escKey = 27
    if (event.keyCode === enterKey || event.keyCode === escKey) {
      return false
    }
~~~

Comment (bayleedev) [reply app/components/search.js:30]: Even with this change I still get a beep when I hit `esc`.
