### PR TITLE
Fix 'npm install' issue

### LINKED ISSUE #250: Update broken for plugins with subdependencies
### Expected Behavior

When I click `update plugins` it should update the plugins and work correctly.

### Actual Behavior

It deletes the sub-dependencies, only keeping the immediate dependencies. Causing the dependencies to break.

### Steps to reproduce the behavior

* Clean out your plugins `rm -rf ~/.zazu/plugins`
* Only have `tinytacoteam/zazu-calculator` to your `plugins`
* ASSERT it was installed `3*3`
* Click `update plugins`
* ASSERT calculator is broken

### Versions

* Zazu: v0.4.0
* OS: Mac Sierra
* GIT: 2.9.2

### Additional Details

This appears to be a problem with npm. I've created a [ticket](https://github.com/npm/npm/issues/15852) with them.

A possible solution is switching to yarn, since a few plugins are already using yarn this could be a good feature, and if it fixes the problem we won't have to wait on a bugfix.

### PR DESCRIPTION
**Pull request by afaur**
Sub-dependencies were not installing after updating plugins while zaza was running.  This fixes the issue by clearing node require cache only after zazu installs each plugin.

@eldinoyev could you take a look at this when you have time?

Fixes #250

### CODE REVIEW

**Comment by eldinoyev** [comment]
Hey, sorry I couldn't get to this sooner, I'll take a look tomorrow.

On Feb 26, 2017 12:44 AM, "Adam Faur" <notifications@github.com> wrote:

@afaur <https://github.com/afaur> requested your review on:
tinytacoteam/zazu#252 <https://github.com/tinytacoteam/zazu/pull/252> Fix
'npm install' issue.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/tinytacoteam/zazu/pull/252#event-977314738>, or mute
the thread

File: app/lib/manager.js [hunk 1]
```diff
@@ -0,0 +1,55 @@
+const manager = (fn, warmupFn, cooldownFn) => {
```
Comment (bayleedev) [inline app/lib/manager.js:1]: I think you made a unit test for this file, it would be awesome to see this in the repo.

File: app/lib/npmInstall.js [hunk 2]
```diff
@@ -11,7 +12,7 @@ const installStatus = require('./installStatus')
  *
  * On failure, returns a rejected promise, so `retry` runs it again.
  */
-const npmInstall = (name, packagePath) => {
+const npmInstall = cooldown((name, packagePath) => {
```
Comment (bayleedev) [inline app/lib/npmInstall.js:15]: A unit test that installs and updates in the same test could be a good end to end test. There are already tests to do both, just not in the same test.

**Comment by bayleedev** [comment]
I added the unit and cucumber spec. Merging.
